# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=20)),
                ('to_addr', models.TextField(default=b'')),
                ('photo', models.TextField(blank=True, default=b'', null=True)),
                ('info', models.TextField(blank=True, default=b'', null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default=b'', max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatorID', models.DecimalField(decimal_places=0, max_digits=10)),
                ('isRide', models.BooleanField(default=False)),
                ('third_Party', models.BooleanField(default=False)),
                ('from_addr', models.TextField(blank=True)),
                ('seats', models.PositiveIntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('car_info', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=25)),
                ('photo', models.TextField(blank=True)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_posts', to='gepu.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='gepu.Event'),
        ),
        migrations.AddField(
            model_name='post',
            name='users',
            field=models.ManyToManyField(default=-1, related_name='posts', to='gepu.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(default=-1, null=True, related_name='_group_admins_+', to='gepu.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(default=-1, null=True, related_name='groups', to='gepu.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='gepu.Group'),
        ),
    ]
