# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 00:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gepu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_eid', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(default=b'', max_length=20)),
                ('to_addr', models.TextField(default=b'')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('info', models.TextField(blank=True, default=b'', null=True)),
                ('photo', models.TextField(blank=True, default=b'', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('hash_code', models.CharField(default=b'BEEF', max_length=4, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=True)),
                ('whitelist', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('valid_util', models.DateTimeField(default=gepu.models.five_days_valid)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hash', to='gepu.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRide', models.BooleanField(default=False)),
                ('third_Party', models.BooleanField(default=False)),
                ('from_addr', models.TextField(blank=True)),
                ('to_addr', models.TextField(blank=True)),
                ('seats', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_info', models.CharField(blank=True, max_length=25)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('fb_id', models.BigIntegerField(blank=True, null=True)),
                ('fbtoken', models.TextField(blank=True)),
                ('messenger_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=25)),
                ('photo', models.TextField(blank=True)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_posts', to='gepu.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='gepu.Event'),
        ),
        migrations.AddField(
            model_name='post',
            name='users',
            field=models.ManyToManyField(blank=True, default=-1, null=True, related_name='posts', to='gepu.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='hosts',
            field=models.ManyToManyField(default=-1, related_name='your_events', to='gepu.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(default=-1, related_name='events', to='gepu.User'),
        ),
    ]
